Microservices/FrontEnds/Course.Web/Models/UserViewModel.cs
namespace Course.Web.Models;

public class UserViewModel
{
    public string Id { get; set; }
    public string UserName { get; set; }
    public string Email { get; set; }
    public string City { get; set; }

    public IEnumerable<string> GetUserProps()
    {
        yield return UserName;
        yield return Email;
        yield return City;
    }
}

Microservices/FrontEnds/Course.Web/Controllers/CoursesController.cs
using Course.Shared.Services;
using Course.Web.Models.Catalogs;
using Course.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Course.Web.Controllers;

[Authorize]
public class CoursesController : Controller
{
    private readonly ICatalogService _catalogService;
    private readonly ISharedIdentityService _sharedIdentityService;

    public CoursesController(ICatalogService catalogService, ISharedIdentityService sharedIdentityService)
    {
        _catalogService = catalogService;
        _sharedIdentityService = sharedIdentityService;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _catalogService.GetAllCourseByUserIdAsync(_sharedIdentityService.GetUserId));
    }

    public async Task<IActionResult> Create()
    {
        var categories = await _catalogService.GetAllCategoryAsync();

        ViewBag.categoryList = new SelectList(categories, "Id", "Name");

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(CourseCreateInput courseCreateInput)
    {
        var categories = await _catalogService.GetAllCategoryAsync();
        ViewBag.categoryList = new SelectList(categories, "Id", "Name");
        courseCreateInput.UserId = _sharedIdentityService.GetUserId;
        //courseCreateInput.Picture = "not";
        if (ModelState.IsValid)
        {
            return View();
        }

        await _catalogService.CreateCourseAsync(courseCreateInput);

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Update(string id)
    {
        var course = await _catalogService.GetByCourseId(id);
        var categories = await _catalogService.GetAllCategoryAsync();

        if (course == null)
        {
            //mesaj göster
            RedirectToAction(nameof(Index));
        }
        ViewBag.categoryList = new SelectList(categories, "Id", "Name", course.Id);
        CourseUpdateInput courseUpdateInput = new()
        {
            Id = course.Id,
            Name = course.Name,
            Description = course.Description,
            Price = course.Price,
            Feature = course.Feature,
            CategoryId = course.CategoryId,
            UserId = course.UserId,
            Picture = course.Picture
        };

        return View(courseUpdateInput);
    }

    [HttpPost]
    public async Task<IActionResult> Update(CourseUpdateInput courseUpdateInput)
    {
        var categories = await _catalogService.GetAllCategoryAsync();
        ViewBag.categoryList = new SelectList(categories, "Id", "Name", courseUpdateInput.Id);
        if (!ModelState.IsValid)
        {
            return View();
        }
        await _catalogService.UpdateCourseAsync(courseUpdateInput);

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(string id)
    {
        await _catalogService.DeleteCourseAsync(id);

        return RedirectToAction(nameof(Index));
    }
}

Microservices/FrontEnds/Course.Web/Controllers/UserController.cs
using Course.Web.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Course.Web.Controllers;

public class UserController : Controller
{
    private readonly IUserService _userService;

    public UserController(IUserService userService)
    {
        _userService = userService;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _userService.GetUser());
    }
}

Microservices/FrontEnds/Course.Web/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model UserViewModel
<div class="row">

    <div class="col-md-9">

        <div class="card">
            <div class="card-body">

                <h5 class="card-title">User Information</h5>

                <table class="table table-striped">

                    <tr>
                        <td>User Name</td>
                        <td>@Model.UserName</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <td>City</td>
                        <td>@Model.City</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="list-group">

            <a asp-controller="Courses" asp-action="Index" class="list-group-item list-group-item-action">My courses</a>
        </div>
    </div>
</div>